"""
Agent Zero -> Dify DSL 转换器

将 Agent Zero 的 Graph 结构转换为 Dify 的 YAML 格式
"""

from typing import List, Tuple
from ...schemas.graph_structure import GraphStructure
from .schema import DifyApp, DifyWorkflow, DifyGraph, DifyNode, DifyEdge, DifyNodeData
from .mapper import NodeMapper


class AgentZeroToDifyConverter:
    """Agent Zero -> Dify DSL 转换器"""

    def __init__(self, graph: GraphStructure, agent_name: str):
        """
        初始化转换器

        Args:
            graph: Agent Zero Graph 结构
            agent_name: Agent 名称
        """
        self.graph = graph
        self.agent_name = agent_name
        self.node_id_counter = 1
        self.node_id_map = {}  # Agent Zero node.id -> Dify node id

    def convert(self) -> DifyApp:
        """
        执行转换

        Returns:
            Dify App 对象
        """
        # 1. 创建节点
        nodes = self._create_nodes()

        # 2. 创建连线
        edges = self._create_edges(nodes)

        # 3. 构建 Workflow
        workflow = DifyWorkflow(graph=DifyGraph(nodes=nodes, edges=edges))

        # 4. 构建 App
        app = DifyApp(
            app={
                "name": self.agent_name,
                "mode": "advanced-chat",  # Chatflow 模式
                "icon": "🤖",
                "description": self.graph.pattern.description
                or f"{self.agent_name} - Generated by Agent Zero",
                "use_icon_as_answer_icon": False,
            },
            workflow=workflow,
        )

        return app

    def _create_nodes(self) -> List[DifyNode]:
        """
        创建所有节点

        Returns:
            Dify 节点列表
        """
        nodes = []

        # 1. Start 节点 (必须)
        start_node = self._create_start_node()
        nodes.append(start_node)

        # 2. 转换 Agent Zero 节点
        node_position_index = 0
        for node in self.graph.nodes:
            # 跳过 RAG 节点（Dify 需要手动配置知识库）
            if node.type == "rag":
                print(
                    f"⚠️  跳过 RAG 节点 '{node.id}'（需要在 Dify 中手动添加 Knowledge Retrieval 节点）"
                )
                # 不分配 node_id，这样引用此节点的边也会被跳过
                continue

            dify_node_id = str(self.node_id_counter)
            self.node_id_counter += 1
            self.node_id_map[node.id] = dify_node_id

            # 计算位置 (简单横向布局)
            node_position_index += 1
            position = {"x": node_position_index * 300, "y": 100}

            # 根据类型映射
            if node.type == "llm":
                dify_node = NodeMapper.map_llm_node(node, dify_node_id, position)
            elif node.type == "tool":
                dify_node = NodeMapper.map_tool_node(node, dify_node_id, position)
            elif node.type == "conditional":
                dify_node = NodeMapper.map_conditional_node(node, dify_node_id, position)
            else:
                # 其他类型转为自定义节点
                dify_node = NodeMapper.map_custom_node(node, dify_node_id, position)

            nodes.append(dify_node)

        # 3. Answer 节点 (必须)
        answer_node = self._create_answer_node(len(nodes))
        nodes.append(answer_node)

        return nodes

    def _create_start_node(self) -> DifyNode:
        """
        创建 Start 节点

        Returns:
            Start 节点
        """
        start_id = str(self.node_id_counter)
        self.node_id_counter += 1
        self.node_id_map["START"] = start_id

        # 映射 State 字段为 Start 节点 Variables
        variables = [
            {"variable": "query", "type": "text-input", "label": "用户输入", "required": True}
        ]

        # 添加 State 字段作为可选输入
        for field in self.graph.state_schema.fields:
            if field.name not in ["messages", "trace_file"]:  # 排除内部字段
                variables.append(
                    {
                        "variable": field.name,
                        "type": self._map_field_type(field.type),
                        "label": field.description or field.name,
                        "required": False,
                    }
                )

        return DifyNode(
            id=start_id,
            data=DifyNodeData(title="开始", type="start", variables=variables),
            position={"x": 0, "y": 100},
        )

    def _map_field_type(self, field_type: str) -> str:
        """
        映射 State 字段类型到 Dify 输入类型

        Args:
            field_type: Agent Zero 字段类型

        Returns:
            Dify 输入类型
        """
        mapping = {
            "str": "text-input",
            "int": "number-input",
            "bool": "select",
            "List[str]": "text-input",  # 简化处理
        }
        return mapping.get(field_type, "text-input")

    def _create_answer_node(self, index: int) -> DifyNode:
        """
        创建 Answer 节点

        Args:
            index: 节点索引（用于计算位置）

        Returns:
            Answer 节点
        """
        answer_id = str(self.node_id_counter)
        self.node_id_counter += 1
        self.node_id_map["END"] = answer_id

        return DifyNode(
            id=answer_id,
            data=DifyNodeData(
                title="回答", type="answer", answer="{{#llm.text#}}"  # 引用最后一个 LLM 节点的输出
            ),
            position={"x": index * 300, "y": 100},
        )

    def _create_edges(self, nodes: List[DifyNode]) -> List[DifyEdge]:
        """
        创建连线

        Args:
            nodes: 节点列表

        Returns:
            边列表
        """
        edges = []
        edge_counter = 1

        # 1. Start -> Entry Point
        entry_point_id = self.node_id_map.get(self.graph.entry_point)
        if entry_point_id:
            edges.append(
                DifyEdge(
                    id=f"edge_{edge_counter}",
                    source=self.node_id_map["START"],
                    target=entry_point_id,
                )
            )
            edge_counter += 1

        # 2. 转换普通边
        for edge in self.graph.edges:
            source_id = self.node_id_map.get(edge.source)
            target_id = self.node_id_map.get(edge.target)

            if source_id and target_id:
                edges.append(
                    DifyEdge(id=f"edge_{edge_counter}", source=source_id, target=target_id)
                )
                edge_counter += 1

        # 3. 转换条件边 (使用 Code Node + If-Else 组合)
        for cond_edge in self.graph.conditional_edges:
            source_id = self.node_id_map.get(cond_edge.source)

            if not source_id:
                continue

            # 创建 Code Node 执行条件逻辑
            code_node_id = str(self.node_id_counter)
            self.node_id_counter += 1

            code_node = DifyNode(
                id=code_node_id,
                data=DifyNodeData(
                    title=f"Condition: {cond_edge.condition}",
                    type="code",
                    desc="执行条件判断逻辑",
                    code=cond_edge.condition_logic or "# 条件逻辑\nresult = 'end'",
                    code_language="python3",
                    outputs={"result": {"type": "string", "children": None}},
                ),
                position={"x": (len(nodes) + edge_counter) * 300, "y": 200},
            )
            nodes.append(code_node)

            # Source -> Code Node
            edges.append(DifyEdge(id=f"edge_{edge_counter}", source=source_id, target=code_node_id))
            edge_counter += 1

            # 创建 If-Else 节点
            ifelse_node_id = str(self.node_id_counter)
            self.node_id_counter += 1

            # 构建条件列表
            conditions = []
            for key in cond_edge.branches.keys():
                if key != "end":
                    conditions.append(
                        {
                            "variable_selector": ["code", "result"],
                            "comparison_operator": "is",
                            "value": key,
                        }
                    )

            ifelse_node = DifyNode(
                id=ifelse_node_id,
                data=DifyNodeData(
                    title="Route Decision",
                    type="if-else",
                    desc="根据条件结果路由",
                    conditions=conditions,
                ),
                position={"x": (len(nodes) + edge_counter) * 300, "y": 200},
            )
            nodes.append(ifelse_node)

            # Code Node -> If-Else
            edges.append(
                DifyEdge(id=f"edge_{edge_counter}", source=code_node_id, target=ifelse_node_id)
            )
            edge_counter += 1

            # If-Else -> Targets
            for key, target in cond_edge.branches.items():
                if target == "END":
                    target_id = self.node_id_map.get("END")
                else:
                    target_id = self.node_id_map.get(target)

                if target_id:
                    edges.append(
                        DifyEdge(
                            id=f"edge_{edge_counter}",
                            source=ifelse_node_id,
                            target=target_id,
                            sourceHandle=key,
                        )
                    )
                    edge_counter += 1

        return edges
