"""Curated tool definitions for Agent Zero v8.0.

This module contains a comprehensive list of tools from LangChain Community,
including both hand-picked curated tools and auto-discovered ones.
"""

# 全量工具列表 - 包含精选和扫描发现的工具
CURATED_TOOLS = [
    {
        "id": 'duckduckgo_search',
        "name": 'DuckDuckGo Search',
        "description": '联网搜索工具,用于查询实时信息、新闻、百科等。无需API Key,完全免费。适用于一般性网络搜索。',
        "package_name": 'duckduckgo-search',
        "import_path": 'langchain_community.tools.DuckDuckGoSearchRun',
        "category": 'search',
        "requires_api_key": False,
        "tags": ['search', 'web', 'internet', 'free'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '搜索查询关键词'}}, 'required': ['query']},
        "examples": [{'query': 'Agent Zero 是什么'}, {'query': 'Python 最新版本'}],
    },
    {
        "id": 'tavily_search',
        "name": 'Tavily Search',
        "description": '专为AI优化的搜索引擎,返回结构化的搜索结果。需要API Key,但提供更高质量的搜索结果。',
        "package_name": 'tavily-python',
        "import_path": 'langchain_community.tools.TavilySearchResults',
        "category": 'search',
        "requires_api_key": True,
        "env_var": "TAVILY_API_KEY",
        "tags": ['search', 'web', 'ai-optimized'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '搜索查询'}, 'max_results': {'type': 'integer', 'description': '最大结果数量', 'default': 5}}, 'required': ['query']},
        "examples": [{'query': 'latest AI news', 'max_results': 5}],
    },
    {
        "id": 'arxiv_search',
        "name": 'Arxiv Search',
        "description": '学术论文搜索工具,用于查询物理、计算机科学、数学等领域的科研论文。无需API Key。',
        "package_name": 'arxiv',
        "import_path": 'langchain_community.tools.ArxivQueryRun',
        "category": 'search',
        "requires_api_key": False,
        "tags": ['search', 'academic', 'papers', 'research'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '论文搜索查询'}}, 'required': ['query']},
        "examples": [{'query': 'transformer attention mechanism'}],
    },
    {
        "id": 'wikipedia',
        "name": 'Wikipedia',
        "description": '维基百科查询工具,用于获取百科知识和背景信息。无需API Key。',
        "package_name": 'wikipedia',
        "import_path": 'langchain_community.tools.WikipediaQueryRun',
        "category": 'knowledge',
        "requires_api_key": False,
        "tags": ['knowledge', 'encyclopedia', 'wiki'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '维基百科查询'}}, 'required': ['query']},
        "examples": [{'query': 'Artificial Intelligence'}],
    },
    {
        "id": 'google_scholar',
        "name": 'Google Scholar',
        "description": '学术文献搜索引擎，用于查找学术文章、论文、书籍、摘要和法院意见。适用于学术研究和文献综述。',
        "package_name": 'google-search-results',
        "import_path": 'langchain_community.tools.GoogleScholarQueryRun',
        "category": 'search',
        "requires_api_key": True,
        "env_var": "SERPAPI_API_KEY",
        "tags": ['search', 'academic', 'scholar', 'research'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '学术搜索关键词'}}, 'required': ['query']},
        "examples": [{'query': 'deep learning survey'}],
    },
    {
        "id": 'google_search',
        "name": 'Google Search',
        "description": 'Google 搜索引擎，提供最全面的网络搜索结果。需要 SerpApi Key。',
        "package_name": 'google-search-results',
        "import_path": 'langchain_community.tools.GoogleSearchRun',
        "category": 'search',
        "requires_api_key": True,
        "env_var": "SERPAPI_API_KEY",
        "tags": ['search', 'web', 'google'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '搜索查询'}}, 'required': ['query']},
        "examples": [{'query': 'current weather in Tokyo'}],
    },
    {
        "id": 'pubmed',
        "name": 'PubMed',
        "description": '生物医学文献数据库搜索引擎，用于查找生命科学和生物医学主题的references和摘要。',
        "package_name": 'xmltodict',
        "import_path": 'langchain_community.tools.PubMedQueryRun',
        "category": 'search',
        "requires_api_key": False,
        "tags": ['search', 'medical', 'biology', 'science'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '医学搜索查询'}}, 'required': ['query']},
        "examples": [{'query': 'covid-19 vaccine side effects'}],
    },
    {
        "id": 'bing_search',
        "name": 'Bing Search',
        "description": 'Bing 搜索引擎。需要 Azure Bing Search API Key。',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.BingSearchRun',
        "category": 'search',
        "requires_api_key": True,
        "env_var": "BING_SUBSCRIPTION_KEY",
        "tags": ['search', 'web', 'bing'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '搜索查询'}}, 'required': ['query']},
        "examples": [{'query': 'Microsoft news'}],
    },
    {
        "id": 'calculator',
        "name": 'Calculator',
        "description": '基础计算器,用于执行数学运算。支持加减乘除、幂运算等基本数学表达式。',
        "package_name": 'numexpr',
        "import_path": 'langchain.chains.LLMMathChain',
        "category": 'math',
        "requires_api_key": False,
        "tags": ['math', 'calculation', 'arithmetic'],
        "args_schema": {'type': 'object', 'properties': {'expression': {'type': 'string', 'description': "数学表达式,如 '2 + 2' 或 '(10 * 5) / 2'"}}, 'required': ['expression']},
        "examples": [{'expression': '2 + 2'}, {'expression': '(100 - 20) * 1.5'}],
    },
    {
        "id": 'wolfram_alpha',
        "name": 'Wolfram Alpha',
        "description": '强大的计算知识引擎,可以解答复杂数学问题、科学计算、单位转换等。需要API Key。',
        "package_name": 'wolframalpha',
        "import_path": 'langchain_community.utilities.WolframAlphaAPIWrapper',
        "category": 'math',
        "requires_api_key": True,
        "env_var": "WOLFRAM_ALPHA_APPID",
        "tags": ['math', 'science', 'computation', 'knowledge'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': '计算或查询问题'}}, 'required': ['query']},
        "examples": [{'query': 'integrate x^2 from 0 to 10'}],
    },
    {
        "id": 'file_read',
        "name": 'File Read',
        "description": '读取文本文件内容。支持 txt, md, json, yaml, csv 等文本格式。',
        "package_name": 'built-in',
        "import_path": 'langchain_community.tools.file_management.ReadFileTool',
        "category": 'file',
        "requires_api_key": False,
        "tags": ['file', 'read', 'io'],
        "args_schema": {'type': 'object', 'properties': {'file_path': {'type': 'string', 'description': '要读取的文件路径'}}, 'required': ['file_path']},
        "examples": [{'file_path': './data/config.json'}],
    },
    {
        "id": 'file_write',
        "name": 'File Write',
        "description": '写入内容到文本文件。如果文件不存在会自动创建。',
        "package_name": 'built-in',
        "import_path": 'langchain_community.tools.file_management.WriteFileTool',
        "category": 'file',
        "requires_api_key": False,
        "tags": ['file', 'write', 'io'],
        "args_schema": {'type': 'object', 'properties': {'file_path': {'type': 'string', 'description': '要写入的文件路径'}, 'content': {'type': 'string', 'description': '要写入的内容'}}, 'required': ['file_path', 'content']},
        "examples": [{'file_path': './output.txt', 'content': 'Hello World'}],
    },
    {
        "id": 'file_list',
        "name": 'List Directory',
        "description": '列出指定目录下的所有文件和子目录。',
        "package_name": 'built-in',
        "import_path": 'langchain_community.tools.file_management.ListDirectoryTool',
        "category": 'file',
        "requires_api_key": False,
        "tags": ['file', 'directory', 'list'],
        "args_schema": {'type': 'object', 'properties': {'dir_path': {'type': 'string', 'description': '目录路径'}}, 'required': ['dir_path']},
        "examples": [{'dir_path': './data'}],
    },
    {
        "id": 'python_repl',
        "name": 'Python REPL',
        "description": '执行 Python 代码并返回结果。适用于数据处理、计算、简单脚本等。注意:代码在沙盒环境中执行。',
        "package_name": 'built-in',
        "import_path": 'langchain_experimental.tools.PythonREPLTool',
        "category": 'code',
        "requires_api_key": False,
        "tags": ['code', 'python', 'execution', 'repl'],
        "args_schema": {'type': 'object', 'properties': {'code': {'type': 'string', 'description': '要执行的 Python 代码'}}, 'required': ['code']},
        "examples": [{'code': 'print([i**2 for i in range(10)])'}],
    },
    {
        "id": 'shell',
        "name": 'Shell Command',
        "description": '执行 Shell 命令。⚠️ 谨慎使用,仅在安全环境中执行可信命令。',
        "package_name": 'built-in',
        "import_path": 'langchain_community.tools.shell.ShellTool',
        "category": 'code',
        "requires_api_key": False,
        "tags": ['shell', 'command', 'terminal'],
        "args_schema": {'type': 'object', 'properties': {'command': {'type': 'string', 'description': '要执行的 Shell 命令'}}, 'required': ['command']},
        "examples": [{'command': 'ls -la'}],
    },
    {
        "id": 'requests_get',
        "name": 'HTTP GET Request',
        "description": '发送 HTTP GET 请求获取网页内容或 API 数据。',
        "package_name": 'requests',
        "import_path": 'langchain_community.tools.requests.RequestsGetTool',
        "category": 'web',
        "requires_api_key": False,
        "tags": ['http', 'api', 'web', 'requests'],
        "args_schema": {'type': 'object', 'properties': {'url': {'type': 'string', 'description': '请求的 URL'}}, 'required': ['url']},
        "examples": [{'url': 'https://api.github.com/users/octocat'}],
    },
    {
        "id": 'requests_post',
        "name": 'HTTP POST Request',
        "description": '发送 HTTP POST 请求,用于提交数据到 API。',
        "package_name": 'requests',
        "import_path": 'langchain_community.tools.requests.RequestsPostTool',
        "category": 'web',
        "requires_api_key": False,
        "tags": ['http', 'api', 'web', 'requests', 'post'],
        "args_schema": {'type': 'object', 'properties': {'url': {'type': 'string', 'description': '请求的 URL'}, 'data': {'type': 'object', 'description': 'POST 数据 (JSON 格式)'}}, 'required': ['url', 'data']},
        "examples": [{'url': 'https://httpbin.org/post', 'data': {'key': 'value'}}],
    },
    {
        "id": 'json_parser',
        "name": 'JSON Parser',
        "description": '解析 JSON 字符串并提取数据。',
        "package_name": 'built-in',
        "import_path": 'langchain.tools.json.tool.JsonSpec',
        "category": 'data',
        "requires_api_key": False,
        "tags": ['json', 'parser', 'data'],
        "args_schema": {'type': 'object', 'properties': {'json_string': {'type': 'string', 'description': 'JSON 字符串'}, 'query': {'type': 'string', 'description': 'JSON Path 查询'}}, 'required': ['json_string']},
        "examples": [{'json_string': '{"name": "Alice", "age": 30}', 'query': '$.name'}],
    },
    {
        "id": 'csv_reader',
        "name": 'CSV Reader',
        "description": '读取和查询 CSV 文件数据。',
        "package_name": 'pandas',
        "import_path": 'langchain_experimental.tools.python.tool.PythonAstREPLTool',
        "category": 'data',
        "requires_api_key": False,
        "tags": ['csv', 'data', 'pandas'],
        "args_schema": {'type': 'object', 'properties': {'file_path': {'type': 'string', 'description': 'CSV 文件路径'}}, 'required': ['file_path']},
        "examples": [{'file_path': './data.csv'}],
    },
    {
        "id": 'datetime',
        "name": 'DateTime Tool',
        "description": '获取当前日期时间,或进行日期时间计算。',
        "package_name": 'built-in',
        "import_path": 'langchain.tools.datetime.tool.DatetimeTool',
        "category": 'utility',
        "requires_api_key": False,
        "tags": ['time', 'date', 'datetime'],
        "args_schema": {'type': 'object', 'properties': {'query': {'type': 'string', 'description': "时间查询,如 'now', 'today', 'tomorrow'"}}, 'required': []},
        "examples": [{'query': 'now'}, {}],
    },
    {
        "id": 'amadeusclosestairport',
        "name": 'AmadeusClosestAirport',
        "description": 'Tool for finding the closest airport to a particular location.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.amadeus.AmadeusClosestAirport',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'amadeusclosestairport'],
        "examples": [],
    },
    {
        "id": 'amadeusflightsearch',
        "name": 'AmadeusFlightSearch',
        "description": 'Tool for searching for a single flight between two airports.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.amadeus.AmadeusFlightSearch',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'amadeusflightsearch'],
        "examples": [],
    },
    {
        "id": 'arxivqueryrun',
        "name": 'ArxivQueryRun',
        "description": 'Tool that searches the Arxiv API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.arxiv.ArxivQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'arxivqueryrun'],
        "examples": [],
    },
    {
        "id": 'asknewssearch',
        "name": 'AskNewsSearch',
        "description": 'Tool that searches the AskNews API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.asknews.AskNewsSearch',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'asknewssearch'],
        "examples": [],
    },
    {
        "id": 'huggingfacetexttospeechmodelinference',
        "name": 'HuggingFaceTextToSpeechModelInference',
        "description": 'HuggingFace Text-to-Speech Model Inference.\n\nRequirements:\n    - Environment variable ``HUGGINGFACE_API_KEY`` must be set,\n      or passed as a named parameter to the constructor.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.audio.HuggingFaceTextToSpeechModelInference',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'huggingfacetexttospeechmodelinference'],
        "examples": [],
    },
    {
        "id": 'azureaiservicesdocumentintelligencetool',
        "name": 'AzureAiServicesDocumentIntelligenceTool',
        "description": 'Tool that queries the Azure AI Services Document Intelligence API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/ai-services/document-intelligence/quickstarts/get-started-sdks-rest-api?view=doc-intel-4.0.0&pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_ai_services.AzureAiServicesDocumentIntelligenceTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azureaiservicesdocumentintelligencetool'],
        "examples": [],
    },
    {
        "id": 'azureaiservicesimageanalysistool',
        "name": 'AzureAiServicesImageAnalysisTool',
        "description": "Tool that queries the Azure AI Services Image Analysis API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/azure/ai-services/computer-vision/quickstarts-sdk/image-analysis-client-library-40\n\nAttributes:\nazure_ai_services_key (Optional[str]): The API key for Azure AI Services.\nazure_ai_services_endpoint (Optional[str]): The endpoint URL for Azure AI Services.\nvisual_features Any: The visual features to analyze in the image, can be set as\n    either strings or azure.ai.vision.imageanalysis.models.VisualFeatures.\n    (e.g. 'TAGS', VisualFeatures.CAPTION).\nimage_analysis_client (Any): The client for interacting\n    with Azure AI Services Image Analysis.\nname (str): The name of the tool.\ndescription (str): A description of the tool,\n    including its purpose and expected input.\n",
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_ai_services.AzureAiServicesImageAnalysisTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azureaiservicesimageanalysistool'],
        "examples": [],
    },
    {
        "id": 'azureaiservicesspeechtotexttool',
        "name": 'AzureAiServicesSpeechToTextTool',
        "description": 'Tool that queries the Azure AI Services Speech to Text API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-speech-to-text?pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_ai_services.AzureAiServicesSpeechToTextTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azureaiservicesspeechtotexttool'],
        "examples": [],
    },
    {
        "id": 'azureaiservicestextanalyticsforhealthtool',
        "name": 'AzureAiServicesTextAnalyticsForHealthTool',
        "description": 'Tool that queries the Azure AI Services Text Analytics for Health API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/ai-services/language-service/text-analytics-for-health/quickstart?pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_ai_services.AzureAiServicesTextAnalyticsForHealthTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azureaiservicestextanalyticsforhealthtool'],
        "examples": [],
    },
    {
        "id": 'azureaiservicestexttospeechtool',
        "name": 'AzureAiServicesTextToSpeechTool',
        "description": 'Tool that queries the Azure AI Services Text to Speech API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/ai-services/speech-service/get-started-text-to-speech?pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_ai_services.AzureAiServicesTextToSpeechTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azureaiservicestexttospeechtool'],
        "examples": [],
    },
    {
        "id": 'azurecogsformrecognizertool',
        "name": 'AzureCogsFormRecognizerTool',
        "description": 'Tool that queries the Azure Cognitive Services Form Recognizer API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/get-started-sdks-rest-api?view=form-recog-3.0.0&pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_cognitive_services.AzureCogsFormRecognizerTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azurecogsformrecognizertool'],
        "examples": [],
    },
    {
        "id": 'azurecogsimageanalysistool',
        "name": 'AzureCogsImageAnalysisTool',
        "description": 'Tool that queries the Azure Cognitive Services Image Analysis API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/cognitive-services/computer-vision/quickstarts-sdk/image-analysis-client-library-40\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_cognitive_services.AzureCogsImageAnalysisTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azurecogsimageanalysistool'],
        "examples": [],
    },
    {
        "id": 'azurecogsspeech2texttool',
        "name": 'AzureCogsSpeech2TextTool',
        "description": 'Tool that queries the Azure Cognitive Services Speech2Text API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-speech-to-text?pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_cognitive_services.AzureCogsSpeech2TextTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azurecogsspeech2texttool'],
        "examples": [],
    },
    {
        "id": 'azurecogstext2speechtool',
        "name": 'AzureCogsText2SpeechTool',
        "description": 'Tool that queries the Azure Cognitive Services Text2Speech API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/get-started-text-to-speech?pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_cognitive_services.AzureCogsText2SpeechTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azurecogstext2speechtool'],
        "examples": [],
    },
    {
        "id": 'azurecogstextanalyticshealthtool',
        "name": 'AzureCogsTextAnalyticsHealthTool',
        "description": 'Tool that queries the Azure Cognitive Services Text Analytics for Health API.\n\nIn order to set this up, follow instructions at:\nhttps://learn.microsoft.com/en-us/azure/ai-services/language-service/text-analytics-for-health/quickstart?tabs=windows&pivots=programming-language-python\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.azure_cognitive_services.AzureCogsTextAnalyticsHealthTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'azurecogstextanalyticshealthtool'],
        "examples": [],
    },
    {
        "id": 'bingsearchresults',
        "name": 'BingSearchResults',
        "description": 'Bing Search tool.\n\nSetup:\n    Install ``langchain-community`` and set environment variable ``BING_SUBSCRIPTION_KEY``.\n\n    .. code-block:: bash\n\n        pip install -U langchain-community\n        export BING_SUBSCRIPTION_KEY="your-api-key"\n\nInstantiation:\n    .. code-block:: python\n\n        from langchain_community.tools.bing_search import BingSearchResults\n        from langchain_community.utilities import BingSearchAPIWrapper\n\n        api_wrapper = BingSearchAPIWrapper()\n        tool = BingSearchResults(api_wrapper=api_wrapper)\n\nInvocation with args:\n    .. code-block:: python\n\n        tool.invoke({"query": "what is the weather in SF?"})\n\n    .. code-block:: python\n\n        "[{\'snippet\': \'<b>San Francisco, CA</b> <b>Weather</b> Forecast, with current conditions, wind, air quality, and what to expect for the next 3 days.\', \'title\': \'San Francisco, CA Weather Forecast | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/weather-forecast/347629\'}, {\'snippet\': \'Tropical Storm Ernesto Forms; Fire <b>Weather</b> Concerns in the Great Basin: Hot Temperatures Return to the South-Central U.S. ... <b>San Francisco CA</b> 37.77°N 122.41°W (Elev. 131 ft) Last Update: 2:21 pm PDT Aug 12, 2024. Forecast Valid: 6pm PDT Aug 12, 2024-6pm PDT Aug 19, 2024 .\', \'title\': \'National Weather Service\', \'link\': \'https://forecast.weather.gov/zipcity.php?inputstring=San+Francisco,CA\'}, {\'snippet\': \'Current <b>weather</b> <b>in San Francisco, CA</b>. Check current conditions <b>in San Francisco, CA</b> with radar, hourly, and more.\', \'title\': \'San Francisco, CA Current Weather | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/current-weather/347629\'}, {\'snippet\': \'Everything you need to know about today&#39;s <b>weather</b> <b>in San Francisco, CA</b>. High/Low, Precipitation Chances, Sunrise/Sunset, and today&#39;s Temperature History.\', \'title\': \'Weather Today for San Francisco, CA | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/weather-today/347629\'}]"\n\nInvocation with ToolCall:\n\n    .. code-block:: python\n\n        tool.invoke({"args": {"query":"what is the weather in SF?"}, "id": "1", "name": tool.name, "type": "tool_call"})\n\n    .. code-block:: python\n\n        ToolMessage(\n            content="[{\'snippet\': \'Get the latest <b>weather</b> forecast for <b>San Francisco, CA</b>, including temperature, RealFeel, and chance of precipitation. Find out how the <b>weather</b> will affect your plans and activities in the city of ...\', \'title\': \'San Francisco, CA Weather Forecast | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/weather-forecast/347629\'}, {\'snippet\': \'Radar. Be prepared with the most accurate 10-day forecast for <b>San Francisco, CA</b> with highs, lows, chance of precipitation from The <b>Weather</b> Channel and <b>Weather</b>.com.\', \'title\': \'10-Day Weather Forecast for San Francisco, CA - The Weather Channel\', \'link\': \'https://weather.com/weather/tenday/l/San+Francisco+CA+USCA0987:1:US\'}, {\'snippet\': \'Tropical Storm Ernesto Forms; Fire <b>Weather</b> Concerns in the Great Basin: Hot Temperatures Return to the South-Central U.S. ... <b>San Francisco CA</b> 37.77°N 122.41°W (Elev. 131 ft) Last Update: 2:21 pm PDT Aug 12, 2024. Forecast Valid: 6pm PDT Aug 12, 2024-6pm PDT Aug 19, 2024 .\', \'title\': \'National Weather Service\', \'link\': \'https://forecast.weather.gov/zipcity.php?inputstring=San+Francisco,CA\'}, {\'snippet\': \'Current <b>weather</b> <b>in San Francisco, CA</b>. Check current conditions <b>in San Francisco, CA</b> with radar, hourly, and more.\', \'title\': \'San Francisco, CA Current Weather | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/current-weather/347629\'}]",\n            artifact=[{\'snippet\': \'Get the latest <b>weather</b> forecast for <b>San Francisco, CA</b>, including temperature, RealFeel, and chance of precipitation. Find out how the <b>weather</b> will affect your plans and activities in the city of ...\', \'title\': \'San Francisco, CA Weather Forecast | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/weather-forecast/347629\'}, {\'snippet\': \'Radar. Be prepared with the most accurate 10-day forecast for <b>San Francisco, CA</b> with highs, lows, chance of precipitation from The <b>Weather</b> Channel and <b>Weather</b>.com.\', \'title\': \'10-Day Weather Forecast for San Francisco, CA - The Weather Channel\', \'link\': \'https://weather.com/weather/tenday/l/San+Francisco+CA+USCA0987:1:US\'}, {\'snippet\': \'Tropical Storm Ernesto Forms; Fire <b>Weather</b> Concerns in the Great Basin: Hot Temperatures Return to the South-Central U.S. ... <b>San Francisco CA</b> 37.77°N 122.41°W (Elev. 131 ft) Last Update: 2:21 pm PDT Aug 12, 2024. Forecast Valid: 6pm PDT Aug 12, 2024-6pm PDT Aug 19, 2024 .\', \'title\': \'National Weather Service\', \'link\': \'https://forecast.weather.gov/zipcity.php?inputstring=San+Francisco,CA\'}, {\'snippet\': \'Current <b>weather</b> <b>in San Francisco, CA</b>. Check current conditions <b>in San Francisco, CA</b> with radar, hourly, and more.\', \'title\': \'San Francisco, CA Current Weather | AccuWeather\', \'link\': \'https://www.accuweather.com/en/us/san-francisco/94103/current-weather/347629\'}],\n            name=\'bing_search_results_json\',\n            tool_call_id=\'1\'\n        )\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.bing_search.BingSearchResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'bingsearchresults'],
        "examples": [],
    },
    {
        "id": 'bingsearchrun',
        "name": 'BingSearchRun',
        "description": 'Tool that queries the Bing search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.bing_search.BingSearchRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'bingsearchrun'],
        "examples": [],
    },
    {
        "id": 'conneryaction',
        "name": 'ConneryAction',
        "description": 'Connery Action tool.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.connery.ConneryAction',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'conneryaction'],
        "examples": [],
    },
    {
        "id": 'dataforseoapisearchresults',
        "name": 'DataForSeoAPISearchResults',
        "description": 'Tool that queries the DataForSeo Google Search API\nand get back json.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.dataforseo_api_search.DataForSeoAPISearchResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'dataforseoapisearchresults'],
        "examples": [],
    },
    {
        "id": 'dataforseoapisearchrun',
        "name": 'DataForSeoAPISearchRun',
        "description": 'Tool that queries the DataForSeo Google search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.dataforseo_api_search.DataForSeoAPISearchRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'dataforseoapisearchrun'],
        "examples": [],
    },
    {
        "id": 'dataheraldtexttosql',
        "name": 'DataheraldTextToSQL',
        "description": 'Tool that queries using the Dataherald SDK.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.dataherald.DataheraldTextToSQL',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'dataheraldtexttosql'],
        "examples": [],
    },
    {
        "id": 'duckduckgosearchrun',
        "name": 'DuckDuckGoSearchRun',
        "description": 'DuckDuckGo tool.\n\nSetup:\n    Install ``duckduckgo-search`` and ``langchain-community``.\n\n    .. code-block:: bash\n\n        pip install -U duckduckgo-search langchain-community\n\nInstantiation:\n    .. code-block:: python\n\n        from langchain_community.tools import DuckDuckGoSearchResults\n\n        tool = DuckDuckGoSearchResults()\n\nInvocation with args:\n    .. code-block:: python\n\n        tool.invoke("Obama")\n\n    .. code-block:: python\n\n        \'[snippet: Users on X have been widely comparing the boost of support felt for Kamala Harris\' campaign to Barack Obama\'s in 2008., title: Surging Support For Kamala Harris Compared To Obama-Era Energy, link: https://www.msn.com/en-us/news/politics/surging-support-for-kamala-harris-compared-to-obama-era-energy/ar-BB1qzdC0, date: 2024-07-24T18:27:01+00:00, source: Newsweek on MSN.com], [snippet: Harris tried to emulate Obama\'s coalition in 2020 and failed. She may have a better shot at reaching young, Black, and Latino voters this time around., title: Harris May Follow Obama\'s Path to the White House After All, link: https://www.msn.com/en-us/news/politics/harris-may-follow-obama-s-path-to-the-white-house-after-all/ar-BB1qv9d4, date: 2024-07-23T22:42:00+00:00, source: Intelligencer on MSN.com], [snippet: The Republican presidential candidate said in an interview on Fox News that he "wouldn\'t be worried" about Michelle Obama running., title: Donald Trump Responds to Michelle Obama Threat, link: https://www.msn.com/en-us/news/politics/donald-trump-responds-to-michelle-obama-threat/ar-BB1qqtu5, date: 2024-07-22T18:26:00+00:00, source: Newsweek on MSN.com], [snippet: H eading into the weekend at his vacation home in Rehoboth Beach, Del., President Biden was reportedly stewing over Barack Obama\'s role in the orchestrated campaign to force him, title: Opinion | Barack Obama Strikes Again, link: https://www.msn.com/en-us/news/politics/opinion-barack-obama-strikes-again/ar-BB1qrfiy, date: 2024-07-22T21:28:00+00:00, source: The Wall Street Journal on MSN.com]\'\n\nInvocation with ToolCall:\n\n    .. code-block:: python\n\n        tool.invoke({"args": {"query":"Obama"}, "id": "1", "name": tool.name, "type": "tool_call"})\n\n    .. code-block:: python\n\n        ToolMessage(content="[snippet: Biden, Obama and the Clintons Will Speak at the Democratic Convention. The president, two of his predecessors and the party\'s 2016 nominee are said to be planning speeches at the party\'s ..., title: Biden, Obama and the Clintons Will Speak at the Democratic Convention ..., link: https://www.nytimes.com/2024/08/12/us/politics/dnc-speakers-biden-obama-clinton.html], [snippet: Barack Obama—with his wife, Michelle—being sworn in as the 44th president of the United States, January 20, 2009. Key events in the life of Barack Obama. Barack Obama (born August 4, 1961, Honolulu, Hawaii, U.S.) is the 44th president of the United States (2009-17) and the first African American to hold the office., title: Barack Obama | Biography, Parents, Education, Presidency, Books ..., link: https://www.britannica.com/biography/Barack-Obama], [snippet: Former President Barack Obama released a letter about President Biden\'s decision to drop out of the 2024 presidential race. Notably, Obama did not name or endorse Vice President Kamala Harris., title: Read Obama\'s full statement on Biden dropping out - CBS News, link: https://www.cbsnews.com/news/barack-obama-biden-dropping-out-2024-presidential-race-full-statement/], [snippet: Many of the marquee names in Democratic politics began quickly lining up behind Vice President Kamala Harris on Sunday, but one towering presence in the party held back: Barack Obama. The former ..., title: Why Obama Hasn\'t Endorsed Harris - The New York Times, link: https://www.nytimes.com/2024/07/21/us/politics/why-obama-hasnt-endorsed-harris.html]", name=\'duckduckgo_results_json\', tool_call_id=\'1\')\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.ddg_search.DuckDuckGoSearchRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'duckduckgosearchrun'],
        "examples": [],
    },
    {
        "id": 'edenaiexplicitimagetool',
        "name": 'EdenAiExplicitImageTool',
        "description": 'Tool that queries the Eden AI Explicit image detection.\n\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/image_explicit_content_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiExplicitImageTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaiexplicitimagetool'],
        "examples": [],
    },
    {
        "id": 'edenaiobjectdetectiontool',
        "name": 'EdenAiObjectDetectionTool',
        "description": 'Tool that queries the Eden AI Object detection API.\n\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/image_object_detection_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiObjectDetectionTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaiobjectdetectiontool'],
        "examples": [],
    },
    {
        "id": 'edenaiparsingidtool',
        "name": 'EdenAiParsingIDTool',
        "description": 'Tool that queries the Eden AI  Identity parsing API.\n\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/ocr_identity_parser_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiParsingIDTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaiparsingidtool'],
        "examples": [],
    },
    {
        "id": 'edenaiparsinginvoicetool',
        "name": 'EdenAiParsingInvoiceTool',
        "description": 'Tool that queries the Eden AI Invoice parsing API.\n\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/ocr_invoice_parser_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiParsingInvoiceTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaiparsinginvoicetool'],
        "examples": [],
    },
    {
        "id": 'edenaispeechtotexttool',
        "name": 'EdenAiSpeechToTextTool',
        "description": 'Tool that queries the Eden AI Speech To Text API.\n\nfor api reference check edenai documentation:\nhttps://app.edenai.run/bricks/speech/asynchronous-speech-to-text.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiSpeechToTextTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaispeechtotexttool'],
        "examples": [],
    },
    {
        "id": 'edenaitextmoderationtool',
        "name": 'EdenAiTextModerationTool',
        "description": 'Tool that queries the Eden AI Explicit text detection.\n\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/image_explicit_content_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiTextModerationTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaitextmoderationtool'],
        "examples": [],
    },
    {
        "id": 'edenaitexttospeechtool',
        "name": 'EdenAiTextToSpeechTool',
        "description": 'Tool that queries the Eden AI Text to speech API.\nfor api reference check edenai documentation:\nhttps://docs.edenai.co/reference/audio_text_to_speech_create.\n\nTo use, you should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenAiTextToSpeechTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaitexttospeechtool'],
        "examples": [],
    },
    {
        "id": 'edenaitool',
        "name": 'EdenaiTool',
        "description": '\nthe base tool for all the EdenAI Tools .\nyou should have\nthe environment variable ``EDENAI_API_KEY`` set with your API token.\nYou can find your token here: https://app.edenai.run/admin/account/settings\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.edenai.EdenaiTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'edenaitool'],
        "examples": [],
    },
    {
        "id": 'elevenlabstext2speechtool',
        "name": 'ElevenLabsText2SpeechTool',
        "description": 'Tool that queries the Eleven Labs Text2Speech API.\n\nIn order to set this up, follow instructions at:\nhttps://elevenlabs.io/docs\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.eleven_labs.ElevenLabsText2SpeechTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'elevenlabstext2speechtool'],
        "examples": [],
    },
    {
        "id": 'fewshotsqltool',
        "name": 'FewShotSQLTool',
        "description": 'Tool to get example SQL queries related to an input question.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.few_shot.FewShotSQLTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'fewshotsqltool'],
        "examples": [],
    },
    {
        "id": 'balancesheets',
        "name": 'BalanceSheets',
        "description": '\nTool that gets balance sheets for a given ticker over a given period.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.financial_datasets.BalanceSheets',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'balancesheets'],
        "examples": [],
    },
    {
        "id": 'cashflowstatements',
        "name": 'CashFlowStatements',
        "description": '\nTool that gets cash flow statements for a given ticker over a given period.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.financial_datasets.CashFlowStatements',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'cashflowstatements'],
        "examples": [],
    },
    {
        "id": 'incomestatements',
        "name": 'IncomeStatements',
        "description": '\nTool that gets income statements for a given ticker over a given period.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.financial_datasets.IncomeStatements',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'incomestatements'],
        "examples": [],
    },
    {
        "id": 'gmailcreatedraft',
        "name": 'GmailCreateDraft',
        "description": 'Tool that creates a draft email for Gmail.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.gmail.GmailCreateDraft',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'gmailcreatedraft'],
        "examples": [],
    },
    {
        "id": 'gmailgetmessage',
        "name": 'GmailGetMessage',
        "description": 'Tool that gets a message by ID from Gmail.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.gmail.GmailGetMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'gmailgetmessage'],
        "examples": [],
    },
    {
        "id": 'gmailgetthread',
        "name": 'GmailGetThread',
        "description": 'Tool that gets a thread by ID from Gmail.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.gmail.GmailGetThread',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'gmailgetthread'],
        "examples": [],
    },
    {
        "id": 'gmailsearch',
        "name": 'GmailSearch',
        "description": 'Tool that searches for messages or threads in Gmail.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.gmail.GmailSearch',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'gmailsearch'],
        "examples": [],
    },
    {
        "id": 'gmailsendmessage',
        "name": 'GmailSendMessage',
        "description": 'Tool that sends a message to Gmail.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.gmail.GmailSendMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'gmailsendmessage'],
        "examples": [],
    },
    {
        "id": 'goldenqueryrun',
        "name": 'GoldenQueryRun',
        "description": 'Tool that adds the capability to query using the Golden API and get back JSON.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.golden_query.GoldenQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'goldenqueryrun'],
        "examples": [],
    },
    {
        "id": 'googlecloudtexttospeechtool',
        "name": 'GoogleCloudTextToSpeechTool',
        "description": '!!! deprecated "0.0.33 Use ``langchain_google_community.TextToSpeechTool`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Google Cloud Text to Speech API.\n\nIn order to set this up, follow instructions at:\nhttps://cloud.google.com/text-to-speech/docs/before-you-begin',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_cloud.GoogleCloudTextToSpeechTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlecloudtexttospeechtool'],
        "examples": [],
    },
    {
        "id": 'googlefinancequeryrun',
        "name": 'GoogleFinanceQueryRun',
        "description": 'Tool that queries the Google Finance API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_finance.GoogleFinanceQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlefinancequeryrun'],
        "examples": [],
    },
    {
        "id": 'googlejobsqueryrun',
        "name": 'GoogleJobsQueryRun',
        "description": 'Tool that queries the Google Jobs API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_jobs.GoogleJobsQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlejobsqueryrun'],
        "examples": [],
    },
    {
        "id": 'googlelensqueryrun',
        "name": 'GoogleLensQueryRun',
        "description": 'Tool that queries the Google Lens API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_lens.GoogleLensQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlelensqueryrun'],
        "examples": [],
    },
    {
        "id": 'googleplacestool',
        "name": 'GooglePlacesTool',
        "description": '!!! deprecated "0.0.33 Use ``langchain_google_community.GooglePlacesTool`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Google places API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_places.GooglePlacesTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googleplacestool'],
        "examples": [],
    },
    {
        "id": 'googlescholarqueryrun',
        "name": 'GoogleScholarQueryRun',
        "description": 'Tool that queries the Google search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_scholar.GoogleScholarQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlescholarqueryrun'],
        "examples": [],
    },
    {
        "id": 'googlesearchresults',
        "name": 'GoogleSearchResults',
        "description": '!!! deprecated "0.0.33 Use ``langchain_google_community.GoogleSearchResults`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Google Search API and gets back json.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_search.GoogleSearchResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlesearchresults'],
        "examples": [],
    },
    {
        "id": 'googlesearchrun',
        "name": 'GoogleSearchRun',
        "description": '!!! deprecated "0.0.33 Use ``langchain_google_community.GoogleSearchRun`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Google search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_search.GoogleSearchRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googlesearchrun'],
        "examples": [],
    },
    {
        "id": 'googleserperresults',
        "name": 'GoogleSerperResults',
        "description": 'Tool that queries the Serper.dev Google Search API\nand get back json.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_serper.GoogleSerperResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googleserperresults'],
        "examples": [],
    },
    {
        "id": 'googleserperrun',
        "name": 'GoogleSerperRun',
        "description": 'Tool that queries the Serper.dev Google search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_serper.GoogleSerperRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googleserperrun'],
        "examples": [],
    },
    {
        "id": 'googletrendsqueryrun',
        "name": 'GoogleTrendsQueryRun',
        "description": 'Tool that queries the Google trends API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.google_trends.GoogleTrendsQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'googletrendsqueryrun'],
        "examples": [],
    },
    {
        "id": 'human',
        "name": 'human',
        "description": 'You can ask a human for guidance when you think you got stuck or you are not sure what to do next. The input should be a question for the human.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.human.HumanInputRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'human'],
        "examples": [],
    },
    {
        "id": 'jinasearch',
        "name": 'JinaSearch',
        "description": 'Tool that queries the JinaSearch.\n\n..versionadded:: 0.2.16\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.jina_search.JinaSearch',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'jinasearch'],
        "examples": [],
    },
    {
        "id": 'memorize',
        "name": 'Memorize',
        "description": 'Tool that trains a language model.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.memorize.Memorize',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'memorize'],
        "examples": [],
    },
    {
        "id": 'metaphorsearchresults',
        "name": 'MetaphorSearchResults',
        "description": '!!! deprecated "0.0.15 Use `langchain_exa.ExaSearchResults` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Metaphor Search API and gets back json.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.metaphor_search.MetaphorSearchResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'metaphorsearchresults'],
        "examples": [],
    },
    {
        "id": 'close_multion_session',
        "name": 'close_multion_session',
        "description": 'Use this tool to close an existing corresponding Multion Browser Window with provided fields. Note: SessionId must be received from previous Browser window creation.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.multion.MultionCloseSession',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": {'description': 'Input for UpdateSessionTool.', 'properties': {'sessionId': {'description': 'The sessionId, received from one of the createSessions \n        or updateSessions run before', 'title': 'Sessionid', 'type': 'string'}}, 'required': ['sessionId'], 'title': 'CloseSessionSchema', 'type': 'object'},
        "tags": ['community', 'close_multion_session'],
        "examples": [],
    },
    {
        "id": 'create_multion_session',
        "name": 'create_multion_session',
        "description": "\n        Create a new web browsing session based on a user's command or request.         The command should include the full info required for the session.         Also include an url (defaults to google.com if no better option)         to start the session.         Use this tool to create a new Browser Window with provided fields.         Always the first step to run any activities that can be done using browser.\n        ",
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.multion.MultionCreateSession',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": {'description': 'Input for CreateSessionTool.', 'properties': {'query': {'description': 'The query to run in multion agent.', 'title': 'Query', 'type': 'string'}, 'url': {'default': 'https://www.google.com/', 'description': 'The Url to run the agent at. Note: accepts only secure             links having https://', 'title': 'Url', 'type': 'string'}}, 'required': ['query'], 'title': 'CreateSessionSchema', 'type': 'object'},
        "tags": ['community', 'create_multion_session'],
        "examples": [],
    },
    {
        "id": 'update_multion_session',
        "name": 'update_multion_session',
        "description": 'Use this tool to update an existing corresponding Multion Browser Window with provided fields. Note: sessionId must be received from previous Browser window creation.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.multion.MultionUpdateSession',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": {'description': 'Input for UpdateSessionTool.', 'properties': {'sessionId': {'description': 'The sessionID, \n        received from one of the createSessions run before', 'title': 'Sessionid', 'type': 'string'}, 'query': {'description': 'The query to run in multion agent.', 'title': 'Query', 'type': 'string'}, 'url': {'default': 'https://www.google.com/', 'description': 'The Url to run the agent at.         Note: accepts only secure links having https://', 'title': 'Url', 'type': 'string'}}, 'required': ['sessionId', 'query'], 'title': 'UpdateSessionSchema', 'type': 'object'},
        "tags": ['community', 'update_multion_session'],
        "examples": [],
    },
    {
        "id": 'nucliaunderstandingapi',
        "name": 'NucliaUnderstandingAPI',
        "description": 'Tool to process files with the Nuclia Understanding API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.nuclia.NucliaUnderstandingAPI',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'nucliaunderstandingapi'],
        "examples": [],
    },
    {
        "id": 'o365createdraftmessage',
        "name": 'O365CreateDraftMessage',
        "description": 'Tool for creating a draft email in Office 365.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.office365.O365CreateDraftMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'o365createdraftmessage'],
        "examples": [],
    },
    {
        "id": 'o365searchemails',
        "name": 'O365SearchEmails',
        "description": 'Search email messages in Office 365.\n\nFree, but setup is required.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.office365.O365SearchEmails',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'o365searchemails'],
        "examples": [],
    },
    {
        "id": 'o365searchevents',
        "name": 'O365SearchEvents',
        "description": 'Search calendar events in Office 365.\n\nFree, but setup is required\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.office365.O365SearchEvents',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'o365searchevents'],
        "examples": [],
    },
    {
        "id": 'o365sendevent',
        "name": 'O365SendEvent',
        "description": 'Tool for sending calendar events in Office 365.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.office365.O365SendEvent',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'o365sendevent'],
        "examples": [],
    },
    {
        "id": 'o365sendmessage',
        "name": 'O365SendMessage',
        "description": 'Send an email in Office 365.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.office365.O365SendMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'o365sendmessage'],
        "examples": [],
    },
    {
        "id": 'openaidalleimagegenerationtool',
        "name": 'OpenAIDALLEImageGenerationTool',
        "description": 'Tool that generates an image using OpenAI DALLE.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.openai_dalle_image_generation.OpenAIDALLEImageGenerationTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'openaidalleimagegenerationtool'],
        "examples": [],
    },
    {
        "id": 'openweathermapqueryrun',
        "name": 'OpenWeatherMapQueryRun',
        "description": 'Tool that queries the OpenWeatherMap API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.openweathermap.OpenWeatherMapQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'openweathermapqueryrun'],
        "examples": [],
    },
    {
        "id": 'nutritionai',
        "name": 'NutritionAI',
        "description": 'Tool that queries the Passio Nutrition AI API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.passio_nutrition_ai.NutritionAI',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'nutritionai'],
        "examples": [],
    },
    {
        "id": 'clicktool',
        "name": 'ClickTool',
        "description": 'Tool for clicking on an element with the given CSS selector.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.ClickTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'clicktool'],
        "examples": [],
    },
    {
        "id": 'currentwebpagetool',
        "name": 'CurrentWebPageTool',
        "description": 'Tool for getting the URL of the current webpage.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.CurrentWebPageTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'currentwebpagetool'],
        "examples": [],
    },
    {
        "id": 'extracthyperlinkstool',
        "name": 'ExtractHyperlinksTool',
        "description": 'Extract all hyperlinks on the page.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.ExtractHyperlinksTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'extracthyperlinkstool'],
        "examples": [],
    },
    {
        "id": 'extracttexttool',
        "name": 'ExtractTextTool',
        "description": 'Tool for extracting all the text on the current webpage.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.ExtractTextTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'extracttexttool'],
        "examples": [],
    },
    {
        "id": 'getelementstool',
        "name": 'GetElementsTool',
        "description": 'Tool for getting elements in the current web page matching a CSS selector.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.GetElementsTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'getelementstool'],
        "examples": [],
    },
    {
        "id": 'navigatebacktool',
        "name": 'NavigateBackTool',
        "description": 'Navigate back to the previous page in the browser history.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.NavigateBackTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'navigatebacktool'],
        "examples": [],
    },
    {
        "id": 'navigatetool',
        "name": 'NavigateTool',
        "description": "Tool for navigating a browser to a URL.\n\n**Security Note**: This tool provides code to control web-browser navigation.\n\n    This tool can navigate to any URL, including internal network URLs, and\n    URLs exposed on the server itself.\n\n    However, if exposing this tool to end-users, consider limiting network\n    access to the server that hosts the agent.\n\n    By default, the URL scheme has been limited to 'http' and 'https' to\n    prevent navigation to local file system URLs (or other schemes).\n\n    If access to the local file system is required, consider creating a custom\n    tool or providing a custom args_schema that allows the desired URL schemes.\n\n    See https://python.langchain.com/docs/security for more information.\n",
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.playwright.NavigateTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'navigatetool'],
        "examples": [],
    },
    {
        "id": 'polygonaggregates',
        "name": 'PolygonAggregates',
        "description": '\nTool that gets aggregate bars (stock prices) over a\ngiven date range for a given ticker from Polygon.\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.polygon.PolygonAggregates',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'polygonaggregates'],
        "examples": [],
    },
    {
        "id": 'polygonfinancials',
        "name": 'PolygonFinancials',
        "description": 'Tool that gets the financials of a ticker from Polygon',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.polygon.PolygonFinancials',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'polygonfinancials'],
        "examples": [],
    },
    {
        "id": 'polygonlastquote',
        "name": 'PolygonLastQuote',
        "description": 'Tool that gets the last quote of a ticker from Polygon',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.polygon.PolygonLastQuote',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'polygonlastquote'],
        "examples": [],
    },
    {
        "id": 'polygontickernews',
        "name": 'PolygonTickerNews',
        "description": 'Tool that gets the latest news for a given ticker from Polygon',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.polygon.PolygonTickerNews',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'polygontickernews'],
        "examples": [],
    },
    {
        "id": 'searchapiresults',
        "name": 'SearchAPIResults',
        "description": 'Tool that queries the SearchApi.io search API and returns JSON.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.searchapi.SearchAPIResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'searchapiresults'],
        "examples": [],
    },
    {
        "id": 'searchapirun',
        "name": 'SearchAPIRun',
        "description": 'Tool that queries the SearchApi.io search API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.searchapi.SearchAPIRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'searchapirun'],
        "examples": [],
    },
    {
        "id": 'semanticscholarqueryrun',
        "name": 'SemanticScholarQueryRun',
        "description": 'Tool that searches the semanticscholar API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.semanticscholar.SemanticScholarQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'semanticscholarqueryrun'],
        "examples": [],
    },
    {
        "id": 'slackgetchannel',
        "name": 'SlackGetChannel',
        "description": 'Tool that gets Slack channel information.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.slack.SlackGetChannel',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'slackgetchannel'],
        "examples": [],
    },
    {
        "id": 'slackgetmessage',
        "name": 'SlackGetMessage',
        "description": 'Tool that gets Slack messages.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.slack.SlackGetMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'slackgetmessage'],
        "examples": [],
    },
    {
        "id": 'slackschedulemessage',
        "name": 'SlackScheduleMessage',
        "description": 'Tool for scheduling a message in Slack.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.slack.SlackScheduleMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'slackschedulemessage'],
        "examples": [],
    },
    {
        "id": 'slacksendmessage',
        "name": 'SlackSendMessage',
        "description": 'Tool for sending a message in Slack.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.slack.SlackSendMessage',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'slacksendmessage'],
        "examples": [],
    },
    {
        "id": 'steamshipimagegenerationtool',
        "name": 'SteamshipImageGenerationTool',
        "description": 'Tool used to generate images from a text-prompt.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.steamship_image_generation.SteamshipImageGenerationTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'steamshipimagegenerationtool'],
        "examples": [],
    },
    {
        "id": 'tavilyanswer',
        "name": 'TavilyAnswer',
        "description": '!!! deprecated "0.3.25 Use ``langchain_tavily.TavilySearch`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Tavily Search API and gets back an answer.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.tavily_search.TavilyAnswer',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'tavilyanswer'],
        "examples": [],
    },
    {
        "id": 'tavilysearchresults',
        "name": 'TavilySearchResults',
        "description": '!!! deprecated "0.3.25 Use ``langchain_tavily.TavilySearch`` instead. It will not be removed until langchain-community==1.0."\n\nTool that queries the Tavily Search API and gets back json.\n\n    Setup:\n        Install ``langchain-openai`` and ``tavily-python``, and set environment variable ``TAVILY_API_KEY``.\n\n        .. code-block:: bash\n\n            pip install -U langchain-community tavily-python\n            export TAVILY_API_KEY="your-api-key"\n\n    Instantiate:\n\n        .. code-block:: python\n\n            from langchain_community.tools import TavilySearchResults\n\n            tool = TavilySearchResults(\n                max_results=5,\n                include_answer=True,\n                include_raw_content=True,\n                include_images=True,\n                # search_depth="advanced",\n                # include_domains = []\n                # exclude_domains = []\n            )\n\n    Invoke directly with args:\n\n        .. code-block:: python\n\n            tool.invoke({\'query\': \'who won the last french open\'})\n\n        .. code-block:: json\n\n            {\n                "url": "https://www.nytimes.com...",\n                "content": "Novak Djokovic won the last French Open by beating Casper Ruud ..."\n            }\n\n    Invoke with tool call:\n\n        .. code-block:: python\n\n            tool.invoke({"args": {\'query\': \'who won the last french open\'}, "type": "tool_call", "id": "foo", "name": "tavily"})\n\n        .. code-block:: python\n\n            ToolMessage(\n                content=\'{ "url": "https://www.nytimes.com...", "content": "Novak Djokovic won the last French Open by beating Casper Ruud ..." }\',\n                artifact={\n                    \'query\': \'who won the last french open\',\n                    \'follow_up_questions\': None,\n                    \'answer\': \'Novak ...\',\n                    \'images\': [\n                        \'https://www.amny.com/wp-content/uploads/2023/06/AP23162622181176-1200x800.jpg\',\n                        ...\n                        ],\n                    \'results\': [\n                        {\n                            \'title\': \'Djokovic ...\',\n                            \'url\': \'https://www.nytimes.com...\',\n                            \'content\': "Novak...",\n                            \'score\': 0.99505633,\n                            \'raw_content\': \'Tennis\nNovak ...\'\n                        },\n                        ...\n                    ],\n                    \'response_time\': 2.92\n                },\n                tool_call_id=\'1\',\n                name=\'tavily_search_results_json\',\n            )\n\n    ',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.tavily_search.TavilySearchResults',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'tavilysearchresults'],
        "examples": [],
    },
    {
        "id": 'wolframalphaqueryrun',
        "name": 'WolframAlphaQueryRun',
        "description": 'Tool that queries using the Wolfram Alpha SDK.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.wolfram_alpha.WolframAlphaQueryRun',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'wolframalphaqueryrun'],
        "examples": [],
    },
    {
        "id": 'yousearchtool',
        "name": 'YouSearchTool',
        "description": 'Tool that searches the you.com API.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.you.YouSearchTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'yousearchtool'],
        "examples": [],
    },
    {
        "id": 'zapiernlalistactions',
        "name": 'ZapierNLAListActions',
        "description": 'Returns a list of all exposed (enabled) actions associated with\ncurrent user (associated with the set api_key). Change your exposed\nactions here: https://nla.zapier.com/demo/start/\n\nThe return list can be empty if no actions exposed. Else will contain\na list of action objects:\n\n[{\n    "id": str,\n    "description": str,\n    "params": Dict[str, str]\n}]\n\n`params` will always contain an `instructions` key, the only required\nparam. All others optional and if provided will override any AI guesses\n(see "understanding the AI guessing flow" here:\nhttps://nla.zapier.com/docs/using-the-api#ai-guessing)\nTool to list all exposed actions for the user.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.zapier.ZapierNLAListActions',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'zapiernlalistactions'],
        "examples": [],
    },
    {
        "id": 'zapiernlarunaction',
        "name": 'ZapierNLARunAction',
        "description": 'Executes an action that is identified by action_id, must be exposed\n(enabled) by the current user (associated with the set api_key). Change\nyour exposed actions here: https://nla.zapier.com/demo/start/\n\nThe return JSON is guaranteed to be less than ~500 words (350\ntokens) making it safe to inject into the prompt of another LLM\ncall.\nTool to run a specific action from the user\'s exposed actions.\n\nParams:\n    action_id: a specific action ID (from list actions) of the action to execute\n        (the set api_key must be associated with the action owner)\n    instructions: a natural language instruction string for using the action\n        (eg. "get the latest email from Mike Knoop" for "Gmail: find email" action)\n    params: a dict, optional. Any params provided will *override* AI guesses\n        from `instructions` (see "understanding the AI guessing flow" here:\n        https://nla.zapier.com/docs/using-the-api#ai-guessing)\n\n',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.zapier.ZapierNLARunAction',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'zapiernlarunaction'],
        "examples": [],
    },
    {
        "id": 'zenguardtool',
        "name": 'ZenGuardTool',
        "description": 'No description available.',
        "package_name": 'langchain-community',
        "import_path": 'langchain_community.tools.zenguard.ZenGuardTool',
        "category": 'community',
        "requires_api_key": True,
        "args_schema": None,
        "tags": ['community', 'zenguardtool'],
        "examples": [],
    },
]

# 工具统计
TOOL_COUNT = len(CURATED_TOOLS)
CATEGORIES = list(set(tool["category"] for tool in CURATED_TOOLS))
FREE_TOOLS = [tool for tool in CURATED_TOOLS if not tool["requires_api_key"]]
API_KEY_TOOLS = [tool for tool in CURATED_TOOLS if tool["requires_api_key"]]

print(f"""
📊 Agent Zero v8.0 工具库统计:
- 总工具数: {TOOL_COUNT}
- 分类数: {len(CATEGORIES)}
- 免费工具: {len(FREE_TOOLS)}
- 需要 API Key: {len(API_KEY_TOOLS)}
- 分类: {', '.join(CATEGORIES)}
""")
